site:

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug
  publications:
    output: true
    permalink: /publication/:slug
  fun:
    output: true
    permalink: /fun/:slug
  ux:
    output: true
    permalink: /ux/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "publications"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "fun"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "ux"
    values:
      layout: "post"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page:num/"

gallery_types:
  carousel: Carousel
  grid: Grid
grid_columns:
  two: Two
  three: Three
  four: Four
