basic_settings:
  site_title: Anup S
  favicon_image: /images/faceicon.png

header_settings:
  logo_image: /images/facecircle.svg
  logo_width: 70

menu_settings:
  menu_items:
    - title: 'Work'
      url: '/'
    - title: 'Fun'
      url: '/fun'

footer_settings:
  logo_image: /images/facecircle.svg
  logo_width: 70
  footer_tagline:

grid_settings:
  overlay_opacity: 1
  grid_spacing: 10

contact_settings:
  form_action: 'https://formspree.io/your@email.com'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: 'https://www.medium.com/@anupsathya'
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: 'https://www.behance.net/anupsathya'
  deviantart_url: ''
  github_url: 'https://github.com/anupsathya'
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: 'https://open.spotify.com/user/anupsathya?si=A10c31v8QASyUp4NLzigeA'
  bandcamp_url: ''
  linkedin_url: 'https://www.linkedin.com/in/anupsathya/'

color_settings:
  background_color: '#111'
  background_alt_color: '#5B5B5B'
  text_dark_color: '#CCCBCB'
  text_medium_color: 'rgba(255, 255, 255, 0.9);'
  text_light_color: '#9F9E9E'
  accent_color: '#FEDD20'
  border_color: '#dddddd'
  overlay_background_color: '#000000'
  overlay_text_color: '#ffffff'
  overlay_accent_color: '#272838'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="http://fonts.cdnfonts.com/css/neue-haas-grotesk-text-pro" rel="stylesheet">'
  title_font: 'Neue Haas Grotesk Text Pro, sans-serif'
  body_font: 'Neue Haas Grotesk Text Pro, sans-serif'
  regular_weight: 100
  bold_weight: 600
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
  menu:
    small_size: 13
    medium_size: 13
    large_size: 13
    weight: 300
    letter_spacing: 0
  grid_item_title:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 600
    letter_spacing: 0
  grid_item_subtitle:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 400
    letter_spacing: 0
  h1:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 600
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 600
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 19
    medium_size: 19
    large_size: 19
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 14
    medium_size: 14
    large_size: 14
    weight: 100
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""
